import type { SeriesDef } from '../../shared/types.js';
import { COUNTRY_TR, COUNTRY_TR2 } from './labels.js';

/**
 * Gösterge kataloğu.
 *
 * `confidence` alanı dürüstlük içindir:
 *   verified   → uygulama içinden canlı doğrulandı
 *   documented → kaynağın dokümantasyonundan alındı
 *   verify     → kod büyük olasılıkla doğru ama kendi ortamınızda teyit edin
 *
 * `npm run sources:check` bütün serileri kaynağına karşı sınar ve bu alanı
 * veritabanında günceller; Kaynaklar sayfası sonucu renkli rozetle gösterir.
 * Böylece hiçbir seri "doğrulanmış" görünmeden veri üretmez.
 */
const S = (d: SeriesDef): SeriesDef => d;

export const SERIES: SeriesDef[] = [
  // ══════════════════════════════════════════════════════════════════════════
  // 1) ENFLASYON — Türkiye ve dünya
  // ══════════════════════════════════════════════════════════════════════════
  S({
    id: 'tr.cpi.index',
    category: 'inflation',
    nameTr: 'Türkiye TÜFE (endeks, 2003=100)',
    nameEn: 'Türkiye CPI (index)',
    unit: 'endeks',
    currency: null,
    freq: 'monthly',
    geo: 'TR',
    sourceId: 'evds',
    producerSourceId: 'tuik',
    connector: 'evds',
    params: { code: 'TP.FG.J0', producer: 'TÜİK' },
    verifyUrl: 'https://evds2.tcmb.gov.tr/index.php?/evds/serieMarket/collapse_2/5/DataGroup/turkce/bie_tufe1yi/',
    confidence: 'verify',
    note: 'Endeksi TÜİK üretir, TCMB EVDS dağıtır. Yıllık/aylık değişim panoda endeksten hesaplanır — böylece baz yılı değişse de karşılaştırma bozulmaz.',
    featured: true,
    order: 10,
  }),
  S({
    id: 'tr.ppi.index',
    category: 'inflation',
    nameTr: 'Türkiye Yİ-ÜFE (endeks, 2003=100)',
    nameEn: 'Türkiye Domestic PPI (index)',
    unit: 'endeks',
    currency: null,
    freq: 'monthly',
    geo: 'TR',
    sourceId: 'evds',
    producerSourceId: 'tuik',
    connector: 'evds',
    params: { code: 'TP.TUFE1YI.T1', producer: 'TÜİK' },
    verifyUrl: 'https://evds2.tcmb.gov.tr/index.php?/evds/serieMarket',
    confidence: 'verify',
    note: 'Yurt İçi Üretici Fiyat Endeksi. Sözleşme fiyat farkı hesaplarında en çok kullanılan Türkiye serisidir. Kod teyidi için `npm run evds:find -- üfe`.',
    featured: true,
    order: 11,
  }),
  S({
    id: 'tr.ppi.basicmetals',
    category: 'inflation',
    nameTr: 'Türkiye Yİ-ÜFE — Ana metal sanayi (NACE 24)',
    nameEn: 'Türkiye PPI — Basic metals',
    unit: 'endeks',
    currency: null,
    freq: 'monthly',
    geo: 'TR',
    sourceId: 'evds',
    producerSourceId: 'tuik',
    connector: 'evds',
    params: { code: 'TP.TUFE1YI.S24', producer: 'TÜİK' },
    verifyUrl: 'https://evds2.tcmb.gov.tr/index.php?/evds/serieMarket',
    confidence: 'verify',
    note: 'Sac ve profil alımlarında yurt içi maliyet baskısının resmî ölçüsü. Kod teyidi için `npm run evds:find -- "ana metal"`.',
    order: 12,
  }),
  S({
    id: 'tr.cpi.yoy.wb',
    category: 'inflation',
    nameTr: 'Türkiye enflasyonu (yıllık ortalama, Dünya Bankası)',
    nameEn: 'Türkiye inflation, annual average',
    unit: '%',
    currency: null,
    freq: 'annual',
    geo: 'TR',
    sourceId: 'worldbank',
    connector: 'worldbank',
    params: { country: 'TUR', indicator: 'FP.CPI.TOTL.ZG' },
    verifyUrl: 'https://data.worldbank.org/indicator/FP.CPI.TOTL.ZG?locations=TR',
    confidence: 'documented',
    note: 'EVDS anahtarı olmadan da Türkiye enflasyonunun görünmesini sağlayan yedek seri. Uzun geçmiş için elverişli.',
    order: 13,
  }),
  ...(['TUR', 'DEU', 'ITA', 'CHN', 'USA', 'POL', 'IND'] as const).map((iso, i) =>
    S({
      id: `world.cpi.${iso.toLowerCase()}`,
      category: 'inflation',
      nameTr: `${COUNTRY_TR[iso]} — yıllık enflasyon (IMF WEO)`,
      nameEn: `${iso} — annual inflation (IMF WEO)`,
      unit: '%',
      currency: null,
      freq: 'annual',
      geo: iso.slice(0, 2),
      sourceId: 'imf',
      connector: 'imf',
      params: { indicator: 'PCPIPCH', country: iso },
      verifyUrl: `https://www.imf.org/external/datamapper/PCPIPCH@WEO/${iso}`,
      confidence: 'documented',
      note: 'IMF Dünya Ekonomik Görünümü. Geçmiş yıllar gerçekleşme, ileri yıllar IMF tahminidir — grafikte tahmin dönemi ayrı gösterilir.',
      featured: iso === 'TUR' || iso === 'DEU',
      order: 20 + i,
    }),
  ),
  S({
    id: 'ea.hicp.yoy',
    category: 'inflation',
    nameTr: 'Euro Bölgesi HICP — yıllık değişim',
    nameEn: 'Euro area HICP, annual rate',
    unit: '%',
    currency: null,
    freq: 'monthly',
    geo: 'EA',
    sourceId: 'eurostat',
    connector: 'eurostat',
    params: { dataset: 'prc_hicp_manr', query: 'unit=RCH_A&coicop=CP00&geo=EA20' },
    verifyUrl: 'https://ec.europa.eu/eurostat/databrowser/view/prc_hicp_manr/default/table',
    confidence: 'documented',
    note: 'Avrupa\'nın resmî uyumlaştırılmış tüketici enflasyonu. AB\'li tedarikçi/müşteri fiyat görüşmelerinde referans alınır.',
    featured: true,
    order: 30,
  }),
  S({
    id: 'de.hicp.yoy',
    category: 'inflation',
    nameTr: 'Almanya HICP — yıllık değişim',
    nameEn: 'Germany HICP, annual rate',
    unit: '%',
    currency: null,
    freq: 'monthly',
    geo: 'DE',
    sourceId: 'eurostat',
    connector: 'eurostat',
    params: { dataset: 'prc_hicp_manr', query: 'unit=RCH_A&coicop=CP00&geo=DE' },
    verifyUrl: 'https://ec.europa.eu/eurostat/databrowser/view/prc_hicp_manr/default/table',
    confidence: 'documented',
    order: 31,
  }),
  S({
    id: 'us.cpi.index',
    category: 'inflation',
    nameTr: 'ABD TÜFE (endeks, mevsimsellikten arındırılmış)',
    nameEn: 'US CPI-U (index, SA)',
    unit: 'endeks',
    currency: null,
    freq: 'monthly',
    geo: 'US',
    sourceId: 'fred',
    producerSourceId: 'bls',
    connector: 'fred',
    params: { seriesId: 'CPIAUCSL', producer: 'U.S. Bureau of Labor Statistics' },
    verifyUrl: 'https://fred.stlouisfed.org/series/CPIAUCSL',
    confidence: 'documented',
    note: 'Asıl üretici BLS; FRED yalnızca dağıtır.',
    order: 32,
  }),

  // ══════════════════════════════════════════════════════════════════════════
  // 2) ASGARİ ÜCRET — Türkiye ve dünya
  // ══════════════════════════════════════════════════════════════════════════
  S({
    id: 'tr.minwage.gross',
    category: 'minimum_wage',
    nameTr: 'Türkiye asgari ücret — brüt (aylık)',
    nameEn: 'Türkiye minimum wage, gross monthly',
    unit: 'TL/ay',
    currency: 'TRY',
    freq: 'annual',
    geo: 'TR',
    sourceId: 'csgb',
    connector: 'seed',
    params: { file: 'tr-minimum-wage-gross.csv' },
    verifyUrl: 'https://www.csgb.gov.tr/asgari-ucret/',
    confidence: 'documented',
    note: 'Asgari ücret istatistik değil, Asgari Ücret Tespit Komisyonu kararıdır ve Resmî Gazete\'de yayımlanır. Her satırın karar referansı tohum dosyasında saklanır; yıl içi ek zamlar ayrı dönem olarak tutulur. Uygulamayla gelen tohum veri 2016–2025 dönemini kapsar — sonraki kararları Veri Girişi sayfasından ekleyin.',
    featured: true,
    order: 40,
  }),
  S({
    id: 'tr.minwage.net',
    category: 'minimum_wage',
    nameTr: 'Türkiye asgari ücret — net (aylık)',
    nameEn: 'Türkiye minimum wage, net monthly',
    unit: 'TL/ay',
    currency: 'TRY',
    freq: 'annual',
    geo: 'TR',
    sourceId: 'csgb',
    connector: 'seed',
    params: { file: 'tr-minimum-wage-net.csv' },
    verifyUrl: 'https://www.csgb.gov.tr/asgari-ucret/',
    confidence: 'documented',
    note: 'Bekâr, çocuksuz, AGİ sonrası ilk dilim üzerinden ilan edilen net tutar.',
    featured: true,
    order: 41,
  }),
  S({
    id: 'tr.minwage.employer_cost',
    category: 'minimum_wage',
    nameTr: 'Türkiye asgari ücret — işverene toplam maliyet',
    nameEn: 'Türkiye minimum wage, total employer cost',
    unit: 'TL/ay',
    currency: 'TRY',
    freq: 'annual',
    geo: 'TR',
    sourceId: 'csgb',
    connector: 'seed',
    params: { file: 'tr-minimum-wage-employer-cost.csv' },
    verifyUrl: 'https://www.csgb.gov.tr/asgari-ucret/',
    confidence: 'documented',
    note: 'İşçilik maliyeti planlamasında brüt değil bu satır kullanılır: brüt + SGK işveren payı + işsizlik işveren payı, varsa hazine desteği düşülmeden.',
    featured: true,
    order: 42,
  }),
  ...(['TR', 'DE', 'PL', 'RO', 'BG', 'ES', 'FR', 'HU', 'CZ', 'PT', 'GR'] as const).map((geo, i) =>
    S({
      id: `eu.minwage.${geo.toLowerCase()}`,
      category: 'minimum_wage',
      nameTr: `${COUNTRY_TR2[geo]} — aylık asgari ücret (EUR)`,
      nameEn: `${geo} — monthly minimum wage (EUR)`,
      unit: 'EUR/ay',
      currency: 'EUR',
      freq: 'semiannual',
      geo,
      sourceId: 'eurostat',
      connector: 'eurostat',
      params: { dataset: 'earn_mw_cur', query: `currency=EUR&geo=${geo}` },
      verifyUrl: 'https://ec.europa.eu/eurostat/databrowser/view/earn_mw_cur/default/table',
      confidence: 'documented',
      note: 'Eurostat aday ülke olarak Türkiye\'yi de yayımlar; böylece Türkiye asgari ücreti AB ülkeleriyle aynı para biriminde ve aynı metodolojiyle karşılaştırılabilir.',
      featured: geo === 'TR' || geo === 'PL',
      order: 50 + i,
    }),
  ),
  S({
    id: 'us.minwage.federal',
    category: 'minimum_wage',
    nameTr: 'ABD federal asgari ücret (saatlik)',
    nameEn: 'US federal minimum hourly wage',
    unit: 'USD/saat',
    currency: 'USD',
    freq: 'monthly',
    geo: 'US',
    sourceId: 'fred',
    producerSourceId: 'bls',
    connector: 'fred',
    params: { seriesId: 'FEDMINNFRWG', producer: 'U.S. Department of Labor' },
    verifyUrl: 'https://fred.stlouisfed.org/series/FEDMINNFRWG',
    confidence: 'documented',
    order: 65,
  }),

  // ══════════════════════════════════════════════════════════════════════════
  // 3) SAC METAL — HRC · CRC · Paslanmaz
  // ══════════════════════════════════════════════════════════════════════════
  S({
    id: 'steel.hrc.tr',
    category: 'steel',
    nameTr: 'HRC — sıcak haddelenmiş rulo, Türkiye (ex-works)',
    nameEn: 'HRC hot rolled coil, Türkiye ex-works',
    unit: 'USD/ton',
    currency: 'USD',
    freq: 'weekly',
    geo: 'TR',
    sourceId: 'steel_assessments',
    connector: 'manual',
    params: {},
    verifyUrl: 'https://www.steelorbis.com/celik-fiyatlari/',
    confidence: 'documented',
    note: 'Sac fiyatı bir kamu istatistiği DEĞİLDİR; SteelOrbis/MEPS/Kallanish gibi kuruluşların piyasa değerlendirmesidir ve abonelik gerektirir. Uygulama bu seriyi CSV içe aktarma veya elle giriş ile alır ve her satırın bülten referansını saklar. Ücretsiz vekil göstergeler için aşağıdaki PPI serilerine bakın.',
    featured: true,
    order: 70,
  }),
  S({
    id: 'steel.crc.tr',
    category: 'steel',
    nameTr: 'CRC — soğuk haddelenmiş rulo, Türkiye (ex-works)',
    nameEn: 'CRC cold rolled coil, Türkiye ex-works',
    unit: 'USD/ton',
    currency: 'USD',
    freq: 'weekly',
    geo: 'TR',
    sourceId: 'steel_assessments',
    connector: 'manual',
    params: {},
    verifyUrl: 'https://www.steelorbis.com/celik-fiyatlari/',
    confidence: 'documented',
    note: 'CSV/elle giriş kanalı. Tipik olarak HRC + soğuk haddeleme farkı olarak izlenir; pano ikisi arasındaki farkı otomatik hesaplar.',
    featured: true,
    order: 71,
  }),
  S({
    id: 'steel.stainless.304.eu',
    category: 'steel',
    nameTr: 'Paslanmaz 304 sac — Avrupa teslim fiyatı',
    nameEn: 'Stainless 304 sheet, Europe delivered',
    unit: 'EUR/ton',
    currency: 'EUR',
    freq: 'monthly',
    geo: 'EU',
    sourceId: 'steel_assessments',
    connector: 'manual',
    params: {},
    verifyUrl: 'https://mepsinternational.com/gb/en/products/europe-stainless-steel-prices',
    confidence: 'documented',
    note: 'Paslanmaz fiyatı = taban fiyat + alaşım ek bedeli (alloy surcharge). Ek bedeli üreticiler (Outokumpu, Aperam, Acerinox) her ay kamuya açık yayımlar; taban fiyat abonelik verisidir.',
    featured: true,
    order: 72,
  }),
  S({
    id: 'steel.stainless.surcharge.304',
    category: 'steel',
    nameTr: 'Paslanmaz 304 alaşım ek bedeli (alloy surcharge)',
    nameEn: 'Stainless 304 alloy surcharge',
    unit: 'EUR/ton',
    currency: 'EUR',
    freq: 'monthly',
    geo: 'EU',
    sourceId: 'steel_assessments',
    connector: 'manual',
    params: {},
    verifyUrl: 'https://www.outokumpu.com/en/products/alloy-surcharges',
    confidence: 'documented',
    note: 'Üreticilerin aylık ilan ettiği, nikel-krom-molibden borsa fiyatlarından türeyen açık bileşen. Paslanmaz fiyat oynaklığının büyük kısmını bu kalem açıklar.',
    order: 73,
  }),
  S({
    id: 'lme.nickel',
    category: 'steel',
    nameTr: 'Nikel — küresel fiyat (paslanmaz ek bedelinin sürükleyicisi)',
    nameEn: 'Nickel, global price',
    unit: 'USD/ton',
    currency: 'USD',
    freq: 'monthly',
    geo: 'WORLD',
    sourceId: 'fred',
    producerSourceId: 'imf',
    connector: 'fred',
    params: { seriesId: 'PNICKUSDM', producer: 'IMF Primary Commodity Prices / LME' },
    verifyUrl: 'https://fred.stlouisfed.org/series/PNICKUSDM',
    confidence: 'documented',
    note: 'IMF birincil emtia fiyatları serisi, LME nikel kotasyonuna dayanır. Paslanmaz ek bedeli buradan hareketle önceden kestirilebilir.',
    featured: true,
    order: 74,
  }),
  S({
    id: 'us.ppi.steel_mill',
    category: 'steel',
    nameTr: 'ABD ÜFE — çelik hadde ürünleri',
    nameEn: 'US PPI — steel mill products',
    unit: 'endeks',
    currency: null,
    freq: 'monthly',
    geo: 'US',
    sourceId: 'fred',
    producerSourceId: 'bls',
    connector: 'fred',
    params: { seriesId: 'WPU1017', producer: 'U.S. Bureau of Labor Statistics' },
    verifyUrl: 'https://fred.stlouisfed.org/series/WPU1017',
    confidence: 'verify',
    note: 'Ücretsiz ve uzun geçmişli vekil gösterge: mutlak $/ton vermez ama yön ve oynaklık için abonelik gerektirmeyen tek resmî seridir.',
    order: 75,
  }),
  S({
    id: 'us.ppi.hrc_sheet',
    category: 'steel',
    nameTr: 'ABD ÜFE — sıcak haddelenmiş sac ve şerit',
    nameEn: 'US PPI — hot rolled steel sheet and strip',
    unit: 'endeks',
    currency: null,
    freq: 'monthly',
    geo: 'US',
    sourceId: 'fred',
    producerSourceId: 'bls',
    connector: 'fred',
    params: { seriesId: 'WPU101704', producer: 'U.S. Bureau of Labor Statistics' },
    verifyUrl: 'https://fred.stlouisfed.org/series/WPU101704',
    confidence: 'verify',
    note: 'Kod teyidi: `npm run sources:check` ya da FRED arama sayfası. Doğrulanamazsa Kaynaklar sayfasında kırmızı rozetle işaretlenir.',
    order: 76,
  }),
  S({
    id: 'eu.ppi.basicmetals',
    category: 'steel',
    nameTr: 'AB ÜFE — ana metal sanayi (NACE C24)',
    nameEn: 'EU PPI — basic metals (NACE C24)',
    unit: 'endeks',
    currency: null,
    freq: 'monthly',
    geo: 'EU27',
    sourceId: 'eurostat',
    connector: 'eurostat',
    params: { dataset: 'sts_inppd_m', query: 'nace_r2=C24&s_adj=NSA&unit=I21&geo=EU27_2020' },
    verifyUrl: 'https://ec.europa.eu/eurostat/databrowser/view/sts_inppd_m/default/table',
    confidence: 'verify',
    order: 77,
  }),
  S({
    id: 'iron.ore',
    category: 'steel',
    nameTr: 'Demir cevheri — küresel fiyat',
    nameEn: 'Iron ore, global price',
    unit: 'USD/ton',
    currency: 'USD',
    freq: 'monthly',
    geo: 'WORLD',
    sourceId: 'fred',
    producerSourceId: 'imf',
    connector: 'fred',
    params: { seriesId: 'PIORECRUSDM', producer: 'IMF Primary Commodity Prices' },
    verifyUrl: 'https://fred.stlouisfed.org/series/PIORECRUSDM',
    confidence: 'documented',
    note: 'Entegre tesislerin (BF-BOF) hammadde maliyeti. Hurda ile birlikte izlendiğinde sac fiyatının yönü hakkında erken sinyal verir.',
    order: 78,
  }),

  // ══════════════════════════════════════════════════════════════════════════
  // 4) HURDA DEMİR
  // ══════════════════════════════════════════════════════════════════════════
  S({
    id: 'scrap.hms.cfr.turkey',
    category: 'scrap',
    nameTr: 'Hurda HMS 1&2 (80:20) — CFR Türkiye',
    nameEn: 'Scrap HMS 1&2 (80:20) CFR Türkiye',
    unit: 'USD/ton',
    currency: 'USD',
    freq: 'daily',
    geo: 'TR',
    sourceId: 'platts_scrap',
    connector: 'manual',
    params: {},
    verifyUrl: 'https://www.lme.com/en/metals/ferrous/lme-steel-scrap-cfr-turkey-platts',
    confidence: 'documented',
    note: 'Dünya hurda piyasasının fiili referans fiyatı Türkiye ithal hurdasıdır; LME vadeli sözleşmesi bu Platts değerlendirmesine bağlı uzlaşır. Ücretsiz API yoktur — LME günlük uzlaşma fiyatları ve basın bültenlerinden CSV/elle girilir, her satırın kaynağı saklanır.',
    featured: true,
    order: 80,
  }),
  S({
    id: 'us.ppi.scrap',
    category: 'scrap',
    nameTr: 'ABD ÜFE — demir çelik hurdası',
    nameEn: 'US PPI — iron and steel scrap',
    unit: 'endeks',
    currency: null,
    freq: 'monthly',
    geo: 'US',
    sourceId: 'fred',
    producerSourceId: 'bls',
    connector: 'fred',
    params: { seriesId: 'WPU1012', producer: 'U.S. Bureau of Labor Statistics' },
    verifyUrl: 'https://fred.stlouisfed.org/series/WPU1012',
    confidence: 'verify',
    note: 'Hurda için ücretsiz, uzun geçmişli resmî vekil gösterge.',
    featured: true,
    order: 81,
  }),

  // ══════════════════════════════════════════════════════════════════════════
  // 5) AKARYAKIT
  // ══════════════════════════════════════════════════════════════════════════
  S({
    id: 'brent',
    category: 'fuel',
    nameTr: 'Brent ham petrol — spot (Avrupa)',
    nameEn: 'Brent crude oil spot, Europe',
    unit: 'USD/varil',
    currency: 'USD',
    freq: 'daily',
    geo: 'WORLD',
    sourceId: 'fred',
    producerSourceId: 'eia',
    connector: 'fred',
    params: { seriesId: 'DCOILBRENTEU', producer: 'U.S. Energy Information Administration' },
    verifyUrl: 'https://fred.stlouisfed.org/series/DCOILBRENTEU',
    confidence: 'documented',
    note: 'Asıl üretici EIA. Türkiye pompa fiyatının rafineri bileşeni bu fiyattan ve USD/TL kurundan türer.',
    featured: true,
    order: 90,
  }),
  S({
    id: 'tr.gasoline.retail',
    category: 'fuel',
    nameTr: 'Türkiye — kurşunsuz benzin 95 pompa fiyatı (İstanbul)',
    nameEn: 'Türkiye — unleaded 95 pump price (Istanbul)',
    unit: 'TL/litre',
    currency: 'TRY',
    freq: 'weekly',
    geo: 'TR',
    sourceId: 'epdk',
    connector: 'manual',
    params: {},
    verifyUrl: 'https://www.epdk.gov.tr/Detay/Icerik/3-0-72/petrol-piyasasi-fiyatlandirma-raporlari',
    confidence: 'documented',
    note: 'EPDK haftalık fiyatlandırma raporlarını PDF olarak yayımlar; dağıtıcılar (Opet, Petrol Ofisi, Shell) güncel il bazlı liste fiyatlarını sitelerinde ilan eder. Makine okunur açık API bulunmadığından bülten değeri CSV/elle girilir ve rapor referansı saklanır.',
    featured: true,
    order: 91,
  }),
  S({
    id: 'tr.diesel.retail',
    category: 'fuel',
    nameTr: 'Türkiye — motorin pompa fiyatı (İstanbul)',
    nameEn: 'Türkiye — diesel pump price (Istanbul)',
    unit: 'TL/litre',
    currency: 'TRY',
    freq: 'weekly',
    geo: 'TR',
    sourceId: 'epdk',
    connector: 'manual',
    params: {},
    verifyUrl: 'https://www.epdk.gov.tr/Detay/Icerik/3-0-72/petrol-piyasasi-fiyatlandirma-raporlari',
    confidence: 'documented',
    note: 'Nakliye maliyetinin ana girdisi. Sevkiyat fiyatlandırmasında benzinden çok bu seri kullanılır.',
    featured: true,
    order: 92,
  }),
  S({
    id: 'us.gasoline.retail',
    category: 'fuel',
    nameTr: 'ABD — kurşunsuz benzin ortalama pompa fiyatı',
    nameEn: 'US regular gasoline retail price',
    unit: 'USD/galon',
    currency: 'USD',
    freq: 'weekly',
    geo: 'US',
    sourceId: 'fred',
    producerSourceId: 'eia',
    connector: 'fred',
    params: { seriesId: 'GASREGW', producer: 'U.S. Energy Information Administration' },
    verifyUrl: 'https://fred.stlouisfed.org/series/GASREGW',
    confidence: 'documented',
    order: 93,
  }),

  // ══════════════════════════════════════════════════════════════════════════
  // 6) NAVLUN
  // ══════════════════════════════════════════════════════════════════════════
  S({
    id: 'fbx.global',
    category: 'freight',
    nameTr: 'FBX — küresel konteyner spot navlunu',
    nameEn: 'Freightos Baltic Index, global',
    unit: 'USD/FEU',
    currency: 'USD',
    freq: 'weekly',
    geo: 'WORLD',
    sourceId: 'freightos',
    connector: 'manual',
    params: {},
    verifyUrl: 'https://fbx.freightos.com/',
    confidence: 'documented',
    note: 'Baltic Exchange onaylı konteyner spot endeksi. Haftalık değerler sitede kamuya açık yayımlanır; API abonelik gerektirir. FREIGHTOS_API_KEY tanımlarsanız `csvurl` bağlayıcısıyla otomatikleştirilebilir.',
    featured: true,
    order: 100,
  }),
  S({
    id: 'fbx.china_med',
    category: 'freight',
    nameTr: 'FBX11 — Çin/Doğu Asya → Akdeniz',
    nameEn: 'FBX11 China/East Asia to Mediterranean',
    unit: 'USD/FEU',
    currency: 'USD',
    freq: 'weekly',
    geo: 'TR',
    sourceId: 'freightos',
    connector: 'manual',
    params: {},
    verifyUrl: 'https://fbx.freightos.com/',
    confidence: 'documented',
    note: 'Türkiye ithalatı için en anlamlı rota endeksi — Uzak Doğu\'dan Akdeniz limanlarına konteyner spot navlunu.',
    featured: true,
    order: 101,
  }),
  S({
    id: 'wci.composite',
    category: 'freight',
    nameTr: 'Drewry WCI — bileşik konteyner endeksi',
    nameEn: 'Drewry World Container Index, composite',
    unit: 'USD/FEU',
    currency: 'USD',
    freq: 'weekly',
    geo: 'WORLD',
    sourceId: 'drewry',
    connector: 'manual',
    params: {},
    verifyUrl: 'https://www.drewry.co.uk/supply-chain-advisors/supply-chain-expertise/world-container-index-assessed-by-drewry',
    confidence: 'documented',
    note: 'FBX ile çapraz doğrulama için. İkisi ayrışıyorsa piyasa fiyatlaması belirsizdir — sözleşme görüşmelerinde bu bilgi değerlidir.',
    order: 102,
  }),
  S({
    id: 'scfi.composite',
    category: 'freight',
    nameTr: 'SCFI — Şanghay konteyner navlun endeksi',
    nameEn: 'Shanghai Containerized Freight Index',
    unit: 'endeks',
    currency: null,
    freq: 'weekly',
    geo: 'CN',
    sourceId: 'sse_scfi',
    connector: 'manual',
    params: {},
    verifyUrl: 'https://en.sse.net.cn/indices/scfinew.jsp',
    confidence: 'documented',
    note: 'Kaynağındaki resmî borsa endeksi; Çin çıkışlı yüklerde en erken sinyal.',
    order: 103,
  }),
  S({
    id: 'us.ppi.trucking',
    category: 'freight',
    nameTr: 'ABD ÜFE — uzun mesafe karayolu taşımacılığı',
    nameEn: 'US PPI — long-distance truckload freight',
    unit: 'endeks',
    currency: null,
    freq: 'monthly',
    geo: 'US',
    sourceId: 'fred',
    producerSourceId: 'bls',
    connector: 'fred',
    params: { seriesId: 'PCU484121484121', producer: 'U.S. Bureau of Labor Statistics' },
    verifyUrl: 'https://fred.stlouisfed.org/series/PCU484121484121',
    confidence: 'verify',
    note: 'Karayolu navlunu için ücretsiz resmî gösterge.',
    order: 104,
  }),

  // ══════════════════════════════════════════════════════════════════════════
  // 7) ENERJİ — Elektrik ve doğal gaz
  // ══════════════════════════════════════════════════════════════════════════
  S({
    id: 'tr.elec.mcp',
    category: 'energy',
    nameTr: 'Türkiye elektrik PTF — piyasa takas fiyatı (günlük ortalama)',
    nameEn: 'Türkiye day-ahead market clearing price',
    unit: 'TL/MWh',
    currency: 'TRY',
    freq: 'daily',
    geo: 'TR',
    sourceId: 'epias',
    connector: 'epias',
    params: { endpoint: 'mcp', aggregate: 'daily_avg' },
    verifyUrl: 'https://seffaflik.epias.com.tr/electricity/electricity-markets/day-ahead-market-dam/market-clearing-price-mcp',
    confidence: 'verify',
    note: 'Türkiye toptan elektriğinin resmî fiyatı; serbest tüketici sözleşmeleri buna endekslidir. Şeffaflık Platformu 2023\'ten sonra kayıt ve TGT jetonu istemektedir.',
    featured: true,
    order: 110,
  }),
  S({
    id: 'tr.gas.botas.industry',
    category: 'energy',
    nameTr: 'BOTAŞ — sanayi doğal gaz satış fiyatı',
    nameEn: 'BOTAŞ industrial natural gas price',
    unit: 'TL/1000 m³',
    currency: 'TRY',
    freq: 'monthly',
    geo: 'TR',
    sourceId: 'botas',
    connector: 'manual',
    params: {},
    verifyUrl: 'https://www.botas.gov.tr/sayfa/dogal-gaz-satis-fiyatlari/1052',
    confidence: 'documented',
    note: 'BOTAŞ tarifeleri tablo olarak yayımlar; API yoktur. Aylık tarife CSV/elle girilir, tarife yayım tarihi kaynak referansı olarak saklanır.',
    featured: true,
    order: 111,
  }),
  S({
    id: 'eu.elec.nonhousehold',
    category: 'energy',
    nameTr: 'AB — sanayi elektrik fiyatı (vergiler hariç)',
    nameEn: 'EU non-household electricity price, excl. taxes',
    unit: 'EUR/kWh',
    currency: 'EUR',
    freq: 'semiannual',
    geo: 'EU27',
    sourceId: 'eurostat',
    connector: 'eurostat',
    params: { dataset: 'nrg_pc_205', query: 'product=6000&nrg_cons=MWH2000-19999&unit=KWH&tax=X_TAX&currency=EUR&geo=EU27_2020' },
    verifyUrl: 'https://ec.europa.eu/eurostat/databrowser/view/nrg_pc_205/default/table',
    confidence: 'verify',
    note: 'Türkiye bu tabloda aday ülke olarak yer alır — sanayi elektrik maliyetini AB ile aynı temelde karşılaştırmanın tek resmî yoludur.',
    featured: true,
    order: 112,
  }),
  S({
    id: 'tr.elec.nonhousehold',
    category: 'energy',
    nameTr: 'Türkiye — sanayi elektrik fiyatı (vergiler hariç, Eurostat)',
    nameEn: 'Türkiye non-household electricity price, excl. taxes',
    unit: 'EUR/kWh',
    currency: 'EUR',
    freq: 'semiannual',
    geo: 'TR',
    sourceId: 'eurostat',
    connector: 'eurostat',
    params: { dataset: 'nrg_pc_205', query: 'product=6000&nrg_cons=MWH2000-19999&unit=KWH&tax=X_TAX&currency=EUR&geo=TR' },
    verifyUrl: 'https://ec.europa.eu/eurostat/databrowser/view/nrg_pc_205/default/table',
    confidence: 'verify',
    featured: true,
    order: 113,
  }),
  S({
    id: 'eu.gas.nonhousehold',
    category: 'energy',
    nameTr: 'AB — sanayi doğal gaz fiyatı (vergiler hariç)',
    nameEn: 'EU non-household gas price, excl. taxes',
    unit: 'EUR/kWh',
    currency: 'EUR',
    freq: 'semiannual',
    geo: 'EU27',
    sourceId: 'eurostat',
    connector: 'eurostat',
    params: { dataset: 'nrg_pc_203', query: 'product=4100&nrg_cons=GJ1000-3999&unit=KWH&tax=X_TAX&currency=EUR&geo=EU27_2020' },
    verifyUrl: 'https://ec.europa.eu/eurostat/databrowser/view/nrg_pc_203/default/table',
    confidence: 'verify',
    order: 114,
  }),
  S({
    id: 'us.henryhub',
    category: 'energy',
    nameTr: 'Henry Hub — doğal gaz spot fiyatı',
    nameEn: 'Henry Hub natural gas spot price',
    unit: 'USD/MMBtu',
    currency: 'USD',
    freq: 'daily',
    geo: 'US',
    sourceId: 'fred',
    producerSourceId: 'eia',
    connector: 'fred',
    params: { seriesId: 'DHHNGSP', producer: 'U.S. Energy Information Administration' },
    verifyUrl: 'https://fred.stlouisfed.org/series/DHHNGSP',
    confidence: 'documented',
    order: 115,
  }),
  S({
    id: 'eu.gas.import',
    category: 'energy',
    nameTr: 'Avrupa doğal gaz — küresel gösterge fiyat',
    nameEn: 'Natural gas, Europe — global price',
    unit: 'USD/MMBtu',
    currency: 'USD',
    freq: 'monthly',
    geo: 'EU',
    sourceId: 'fred',
    producerSourceId: 'imf',
    connector: 'fred',
    params: { seriesId: 'PNGASEUUSDM', producer: 'IMF Primary Commodity Prices' },
    verifyUrl: 'https://fred.stlouisfed.org/series/PNGASEUUSDM',
    confidence: 'documented',
    note: 'TTF sözleşme fiyatları abonelikli olduğundan Avrupa gaz maliyeti için ücretsiz ve resmî vekil gösterge.',
    featured: true,
    order: 116,
  }),

  // ══════════════════════════════════════════════════════════════════════════
  // 8) KUR — karşılaştırmaları ortak para birimine çevirmek için
  // ══════════════════════════════════════════════════════════════════════════
  S({
    id: 'fx.usdtry',
    category: 'fx',
    nameTr: 'USD/TRY — TCMB gösterge kuru',
    nameEn: 'USD/TRY, CBRT reference rate',
    unit: 'TL',
    currency: 'TRY',
    freq: 'daily',
    geo: 'TR',
    sourceId: 'tcmb_kur',
    producerSourceId: 'ecb',
    connector: 'tcmb_kur',
    params: { currency: 'USD' },
    verifyUrl: 'https://www.tcmb.gov.tr/kurlar/kurlar_tr.html',
    confidence: 'documented',
    note: 'Güncel günün değeri TCMB gösterge kurudur (resmî muhasebe ve gümrük işlemlerinde esas alınan kur). Uzun geçmiş, TCMB günde tek dosya yayımladığı için tek istekle ECB Data Portal\'dan alınıp çapraz kurla türetilir. Para birimi çevrimleri bu seriyle yapılır.',
    featured: true,
    order: 120,
  }),
  S({
    id: 'fx.eurtry',
    category: 'fx',
    nameTr: 'EUR/TRY — TCMB gösterge kuru',
    nameEn: 'EUR/TRY, CBRT reference rate',
    unit: 'TL',
    currency: 'TRY',
    freq: 'daily',
    geo: 'TR',
    sourceId: 'tcmb_kur',
    producerSourceId: 'ecb',
    connector: 'tcmb_kur',
    params: { currency: 'EUR' },
    verifyUrl: 'https://www.tcmb.gov.tr/kurlar/kurlar_tr.html',
    confidence: 'documented',
    featured: true,
    order: 121,
  }),
];

export const SERIES_BY_ID = new Map(SERIES.map((s) => [s.id, s]));
