import type { SourceDef } from '../../shared/types.js';

/**
 * Kaynak kayıt defteri.
 *
 * Kural: her veri için ASIL ÜRETEN kurum "official" olarak listelenir. FRED gibi
 * yeniden yayımcılar "mirror" işaretlidir — veriyi onlar üretmez, BLS/IMF üretir.
 * Bir fiyat gerçekten piyasa değerlendirmesiyle oluşuyorsa (hurda CFR Türkiye,
 * konteyner navlunu) kaynak "benchmark"tır; bunların çoğu aboneliklidir ve
 * uygulama bunları elle/CSV kanalıyla, kaynağı kayda geçirerek alır.
 */
export const SOURCES: SourceDef[] = [
  // ── Türkiye resmî ─────────────────────────────────────────────────────────
  {
    id: 'tuik',
    org: 'Türkiye İstatistik Kurumu (TÜİK)',
    name: 'TÜİK — TÜFE / Yİ-ÜFE',
    tier: 'official',
    homepage: 'https://www.tuik.gov.tr/',
    docsUrl: 'https://data.tuik.gov.tr/Kategori/GetKategori?p=enflasyon-ve-fiyat-106',
    license: 'Kaynak gösterilerek serbestçe kullanılabilir (TÜİK veri politikası).',
    auth: 'manual',
    why: 'Türkiye TÜFE ve Yİ-ÜFE endekslerini üreten tek resmî kurum. Sayısal erişim TCMB EVDS üzerinden yapılır; asıl üretici ve metodoloji sahibi TÜİK\'tir.',
  },
  {
    id: 'evds',
    org: 'Türkiye Cumhuriyet Merkez Bankası (TCMB)',
    name: 'TCMB EVDS — Elektronik Veri Dağıtım Sistemi',
    tier: 'official',
    homepage: 'https://evds2.tcmb.gov.tr/',
    docsUrl: 'https://evds2.tcmb.gov.tr/help/videos/EVDS_Web_Service_Usage_Guide.pdf',
    license: 'Ücretsiz; kayıtla alınan kişisel API anahtarı gerekir. Kaynak gösterimi zorunlu.',
    auth: 'api_key',
    envVar: 'EVDS_API_KEY',
    signupUrl: 'https://evds2.tcmb.gov.tr/index.php?/evds/login',
    why: 'TÜİK ve TCMB serilerinin makine okunur, resmî dağıtım kanalı. Türkiye enflasyon ve fiyat endeksleri için birincil programatik kaynak.',
  },
  {
    id: 'tcmb_kur',
    org: 'Türkiye Cumhuriyet Merkez Bankası (TCMB)',
    name: 'TCMB Günlük Döviz Kurları',
    tier: 'official',
    homepage: 'https://www.tcmb.gov.tr/kurlar/kurlar_tr.html',
    docsUrl: 'https://www.tcmb.gov.tr/wps/wcm/connect/TR/TCMB+TR/Main+Menu/Istatistikler/Doviz+Kurlari/Gosterge+Niteligindeki+Merkez+Bankasi+Kurlari',
    license: 'Kamuya açık, anahtarsız XML servisi.',
    auth: 'none',
    why: 'Türkiye\'de resmî muhasebe ve gümrük işlemlerinde esas alınan kur, TCMB gösterge kurudur. TL karşılaştırmaları bu kurla yapılır.',
  },
  {
    id: 'epdk',
    org: 'Enerji Piyasası Düzenleme Kurumu (EPDK)',
    name: 'EPDK — Akaryakıt fiyat bültenleri ve elektrik tarifeleri',
    tier: 'official',
    homepage: 'https://www.epdk.gov.tr/',
    docsUrl: 'https://www.epdk.gov.tr/Detay/Icerik/3-0-72/petrol-piyasasi-fiyatlandirma-raporlari',
    license: 'Kamuya açık; kaynak gösterilerek kullanılır.',
    auth: 'manual',
    why: 'Türkiye akaryakıt fiyatlarını ve elektrik tarifelerini düzenleyen ve resmî olarak yayımlayan kurum. Dağıtıcı liste fiyatlarının denetleyicisi.',
  },
  {
    id: 'epias',
    org: 'EPİAŞ — Enerji Piyasaları İşletme A.Ş.',
    name: 'EPİAŞ Şeffaflık Platformu',
    tier: 'official',
    homepage: 'https://seffaflik.epias.com.tr/',
    docsUrl: 'https://seffaflik.epias.com.tr/electricity-service/technical/tr/index.html',
    license: 'Ücretsiz; kayıt ve TGT (ticket) ile kimlik doğrulama gerekir.',
    auth: 'login',
    envVar: 'EPIAS_USERNAME',
    signupUrl: 'https://kayit.epias.com.tr/',
    why: 'Türkiye toptan elektrik piyasasının resmî işletmecisi. Piyasa Takas Fiyatı (PTF/MCP) burada oluşur — sanayi elektrik maliyetinin birincil referansı.',
  },
  {
    id: 'botas',
    org: 'BOTAŞ',
    name: 'BOTAŞ Doğal Gaz Satış Fiyatları',
    tier: 'official',
    homepage: 'https://www.botas.gov.tr/',
    docsUrl: 'https://www.botas.gov.tr/sayfa/dogal-gaz-satis-fiyatlari/1052',
    license: 'Kamuya açık tarife tabloları.',
    auth: 'manual',
    why: 'Türkiye\'de sanayi ve elektrik üretimi doğal gaz satış fiyatını belirleyen ve ilan eden kuruluş. Yurt içi gaz maliyetinin resmî kaynağı.',
  },
  {
    id: 'csgb',
    org: 'T.C. Çalışma ve Sosyal Güvenlik Bakanlığı — Asgari Ücret Tespit Komisyonu',
    name: 'Asgari Ücret Tespit Komisyonu Kararları',
    tier: 'official',
    homepage: 'https://www.csgb.gov.tr/asgari-ucret/',
    docsUrl: 'https://www.resmigazete.gov.tr/',
    license: 'Resmî Gazete\'de yayımlanan kamu belgeleri.',
    auth: 'manual',
    why: 'Türkiye asgari ücreti bir istatistik değil, komisyon kararıdır ve Resmî Gazete\'de yayımlanır. Tek doğru kaynak budur; uygulama her yılın değerini karar linkiyle birlikte saklar.',
  },

  // ── Uluslararası resmî ────────────────────────────────────────────────────
  {
    id: 'eurostat',
    org: 'Eurostat — Avrupa Komisyonu',
    name: 'Eurostat Dissemination API',
    tier: 'official',
    homepage: 'https://ec.europa.eu/eurostat',
    docsUrl: 'https://wikis.ec.europa.eu/display/EUROSTATHELP/API+Statistics+-+data+query',
    license: 'Avrupa Komisyonu yeniden kullanım politikası — kaynak gösterimiyle serbest.',
    auth: 'none',
    why: 'AB\'de asgari ücret, sanayi elektrik/doğal gaz fiyatı ve HICP enflasyonunun resmî üreticisi. Türkiye aday ülke olarak birçok tabloda yer alır — Avrupa karşılaştırması için doğru kaynak.',
  },
  {
    id: 'bls',
    org: 'U.S. Bureau of Labor Statistics (BLS)',
    name: 'BLS — Üretici Fiyat Endeksleri (PPI)',
    tier: 'official',
    homepage: 'https://www.bls.gov/ppi/',
    docsUrl: 'https://www.bls.gov/developers/api_signature_v2.htm',
    license: 'ABD kamu verisi — telif korumasız.',
    auth: 'manual',
    why: 'Sıcak/soğuk haddelenmiş sac ve hurda için dünyanın en uzun soluklu, metodolojisi açık üretici fiyat endekslerini yayımlar. Serilerin asıl üreticisi BLS\'tir; uygulama bunları FRED aynası üzerinden çeker.',
  },
  {
    id: 'fred',
    org: 'Federal Reserve Bank of St. Louis',
    name: 'FRED — Federal Reserve Economic Data',
    tier: 'mirror',
    homepage: 'https://fred.stlouisfed.org/',
    docsUrl: 'https://fred.stlouisfed.org/docs/api/fred/',
    license: 'Ücretsiz. Anahtarsız CSV uç noktası da vardır; API anahtarı daha yüksek limit sağlar.',
    auth: 'api_key',
    envVar: 'FRED_API_KEY',
    signupUrl: 'https://fredaccount.stlouisfed.org/apikeys',
    why: 'BLS, EIA ve IMF serilerini tek ve kararlı bir API arkasında toplayan ayna. Veriyi üretmez; asıl üretici her seride ayrıca gösterilir.',
  },
  {
    id: 'eia',
    org: 'U.S. Energy Information Administration (EIA)',
    name: 'EIA Open Data v2',
    tier: 'official',
    homepage: 'https://www.eia.gov/',
    docsUrl: 'https://www.eia.gov/opendata/documentation.php',
    license: 'ABD kamu verisi — ücretsiz API anahtarı gerekir.',
    auth: 'api_key',
    envVar: 'EIA_API_KEY',
    signupUrl: 'https://www.eia.gov/opendata/register.php',
    why: 'Brent ham petrol spot fiyatının ve Henry Hub doğal gaz fiyatının resmî yayımcısı. Akaryakıt ve enerji maliyetinin küresel çıpası.',
  },
  {
    id: 'imf',
    org: 'International Monetary Fund (IMF)',
    name: 'IMF DataMapper API',
    tier: 'official',
    homepage: 'https://www.imf.org/en/Data',
    docsUrl: 'https://www.imf.org/external/datamapper/api/help',
    license: 'Ücretsiz, anahtarsız; kaynak gösterimiyle kullanılır.',
    auth: 'none',
    why: 'Dünya Ekonomik Görünümü (WEO) enflasyon tahmin ve gerçekleşmeleri — ülkeler arası enflasyon karşılaştırmasının standart kaynağı.',
  },
  {
    id: 'worldbank',
    org: 'World Bank',
    name: 'World Bank Open Data API',
    tier: 'official',
    homepage: 'https://data.worldbank.org/',
    docsUrl: 'https://datahelpdesk.worldbank.org/knowledgebase/articles/889392',
    license: 'CC BY 4.0',
    auth: 'none',
    why: 'Neredeyse tüm ülkeler için uzun geçmişli yıllık TÜFE serisi. Küresel enflasyon karşılaştırmasında kapsama açısından en geniş açık kaynak.',
  },
  {
    id: 'ilostat',
    org: 'International Labour Organization (ILO)',
    name: 'ILOSTAT',
    tier: 'official',
    homepage: 'https://ilostat.ilo.org/',
    docsUrl: 'https://ilostat.ilo.org/resources/sdmx-tools/',
    license: 'Kaynak gösterimiyle serbest.',
    auth: 'none',
    why: 'Yasal asgari ücretin küresel, karşılaştırılabilir tek derlemesi. AB dışı ülkeler için asgari ücret verisinin doğru kaynağı.',
  },
  {
    id: 'ecb',
    org: 'European Central Bank (ECB)',
    name: 'ECB Data Portal API',
    tier: 'official',
    homepage: 'https://data.ecb.europa.eu/',
    docsUrl: 'https://data.ecb.europa.eu/help/api/overview',
    license: 'Ücretsiz, anahtarsız.',
    auth: 'none',
    why: 'EUR referans kurlarının resmî kaynağı; USD/EUR çapraz çevrimlerinde kullanılır.',
  },

  // ── Piyasa referansları (abonelikli değerlendirmeler) ─────────────────────
  {
    id: 'platts_scrap',
    org: 'S&P Global Commodity Insights (Platts) / London Metal Exchange',
    name: 'HMS 1&2 (80:20) CFR Türkiye hurda değerlendirmesi',
    tier: 'benchmark',
    homepage: 'https://www.lme.com/en/metals/ferrous/lme-steel-scrap-cfr-turkey-platts',
    docsUrl: 'https://www.spglobal.com/commodityinsights/en/our-methodology/methodology-specifications',
    license: 'Abonelik gerektirir. Günlük gösterge değerleri LME ve basın kanalıyla kamuya açılır.',
    auth: 'manual',
    why: 'Türkiye ithal hurdası dünya hurda piyasasının fiili referans fiyatıdır; LME vadeli sözleşmesi bu değerlendirmeye bağlı uzlaşır. Hurda için "en doğru" fiyat budur — ücretsiz API\'si yoktur, bu yüzden CSV/elle kanalıyla kaynağı kayda geçirilerek girilir.',
  },
  {
    id: 'steel_assessments',
    org: 'SteelOrbis / MEPS International / Kallanish / Argus',
    name: 'HRC · CRC · Paslanmaz sac fiyat değerlendirmeleri',
    tier: 'benchmark',
    homepage: 'https://www.steelorbis.com/celik-fiyatlari/',
    docsUrl: 'https://mepsinternational.com/gb/en/products',
    license: 'Abonelik gerektirir; kurum içi kullanım aboneliğin koşullarına tabidir.',
    auth: 'manual',
    why: 'Sac fiyatı bir istatistik değil, piyasa değerlendirmesidir. Türkiye ve AB için fiili referanslar bu kuruluşlarca üretilir. Uygulama abonelik verisini CSV ile alır ve her satırın bülten referansını saklar.',
  },
  {
    id: 'freightos',
    org: 'Freightos / Baltic Exchange',
    name: 'Freightos Baltic Index (FBX) — konteyner spot navlunu',
    tier: 'benchmark',
    homepage: 'https://terminal.freightos.com/freightos-baltic-index-global-container-pricing-index/',
    docsUrl: 'https://fbx.freightos.com/',
    license: 'Haftalık gösterge değerleri kamuya açık; API abonelik gerektirir.',
    auth: 'manual',
    envVar: 'FREIGHTOS_API_KEY',
    why: 'Baltic Exchange onaylı, konteyner spot navlununun en yaygın kabul gören göstergesi. Rota bazlı (Çin–Avrupa, Çin–Akdeniz) alt endeksleriyle ithalat maliyeti için doğrudan kullanılır.',
  },
  {
    id: 'drewry',
    org: 'Drewry Supply Chain Advisors',
    name: 'World Container Index (WCI)',
    tier: 'benchmark',
    homepage: 'https://www.drewry.co.uk/supply-chain-advisors/supply-chain-expertise/world-container-index-assessed-by-drewry',
    docsUrl: 'https://www.drewry.co.uk/supply-chain-advisors/supply-chain-expertise/world-container-index-assessed-by-drewry',
    license: 'Haftalık bileşik değer sitede ücretsiz yayımlanır; tam veri abonelik gerektirir.',
    auth: 'manual',
    why: 'FBX ile birlikte konteyner navlununun iki ana referansından biri. Haftalık bileşik endeks halka açık yayımlandığı için doğrulanabilir.',
  },
  {
    id: 'sse_scfi',
    org: 'Shanghai Shipping Exchange',
    name: 'SCFI — Shanghai Containerized Freight Index',
    tier: 'benchmark',
    homepage: 'https://en.sse.net.cn/indices/scfinew.jsp',
    docsUrl: 'https://en.sse.net.cn/indices/introduction_scfi.jsp',
    license: 'Haftalık değerler sitede ücretsiz yayımlanır.',
    auth: 'manual',
    why: 'Çin çıkışlı navlunun kaynağındaki resmî borsa endeksi. Uzak Doğu ithalatı ağırlıklı tedarik zincirleri için en erken sinyali verir.',
  },

  // ── Kurum içi ─────────────────────────────────────────────────────────────
  {
    id: 'internal',
    org: 'Kurum içi',
    name: 'Sözleşme ve teklif fiyatları',
    tier: 'manual',
    homepage: '',
    docsUrl: '',
    license: 'Kuruma ait veri.',
    auth: 'manual',
    why: 'Kendi tedarikçi teklifleriniz ve sözleşme fiyatlarınız. Piyasa endeksleriyle aynı eksende karşılaştırılabilsin diye aynı yapıda saklanır.',
  },
];

export const SOURCE_BY_ID = new Map(SOURCES.map((s) => [s.id, s]));
